### ISSUE TITLE
Update documentation for ALB resource

### ISSUE THREAD

**Issue by rmoles** [inspec/inspec-aws#169]
### 🎛 Description

It seems that the ALB resource provides functionality for users to test ALB's and NLB's. It would be worthwhile to update the documentation to reflect this.
Also, it appears that a link to the ALB documentation has been left out of the README.md

**Comment by SowDeu** [comment]
Hi @rmoles ,

Quick note aws_alb method is not working as expected .. issues linked #139. Please help me understand if this is an ongoing issue or new issue. Thanks in advance .

**Comment by rmoles** [comment]
> Hi @rmoles ,
> 
> Quick note aws_alb method is not working as expected .. issues linked #139. Please help me understand if this is an ongoing issue or new issue. Thanks in advance.

Firstly, apologies, it is the ELB class that covers the NLBs rather than ALB. However, the aws_alb class should be available and working. The NoMethodError sounds like there may be an issue with your implementation of the inspec-aws resource pack, or you are using an older version. I would take a look through the README to verify your setup. If the NoMethodError persists I'd suggest checking the FAQ section https://github.com/inspec/inspec-aws#faq

**Comment by SowDeu** [comment]
@rmoles : No problem and thanks for the update .. I will check with ELB method if I can test NLB and update the same.. Fingers Crossed. If I got it right the current version we are using for Inspec is 4.18.24... Not sure if structure is wrong as we are using same structure for other resources and it is working fine.. saying that I might be wrong, I will check once again.

**Comment by SowDeu** [comment]
@rmoles : We have updated inspec chef to new version - 4.18.51 and run a simple test for  : 
TEST: For Testing NLB with ELB
describe aws_elb('nlb-name') do
     it {should exist}
 end
RESULT:
×   AWS ELB nlb-name is expected to exist
     expected AWS ELB nlb-name to exist

TEST: For Testing ELB with ELB
 describe aws_elb('elb_name') do
     it {should exist}
 end
RESULT:
 ✔  elb: AWS ELB elb_name
     ✔  AWS ELB elb_name is expected to exist.
So not sure why it is not picking NLB.

**Comment by rmoles** [comment]
@SowDeu thanks for the feedback. While I investigate further on my end, would you be able to test this using the aws_alb resource, just to verify that this doesn't cover your use case?

**Comment by SowDeu** [comment]
@rmoles : Thanks for the update but  I am unable to test aws_alb resource itself getting below error,      
         
      
         2: from alb.rb:3:in `load_with_context'
         1: from /usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:68:in `method_missing'
/usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:71:in `rescue in method_missing': undefined method `aws_alb' for #<Inspec::ControlEvalContext:0x000056489832ba68> (NoMethodError).

**Comment by SowDeu** [comment]
@rmoles : I have created the profile and still I am getting same issue.. Please help I am new to inspec and I am trying to implement in my work place..Thank you .

**Comment by SowDeu** [comment]
@rmoles  Thank you very much for the support . I can confirm that its ALB Resource that is being used for NLB. It's a formatting error in my profile. Now got it working.
