### ISSUE TITLE
Error launch tests on AWS

### ISSUE THREAD

**Issue by nlamirault** [inspec/inspec-aws#283]
I would like to tests my AWS infra like i do using inspec-gcp and inspec-azure.
But i've got this error : 

```bash
$ inspec exec . -t aws:// --input-file=attributes/staging.yml
Traceback (most recent call last):
        30: from /home/nicolas/.gem/ruby/2.7.0/bin/inspec:23:in `<main>'
        29: from /home/nicolas/.gem/ruby/2.7.0/bin/inspec:23:in `load'
        28: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-bin-4.18.104/bin/inspec:11:in `<top (required)>'
        27: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/base_cli.rb:35:in `start'
        26: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        25: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        24: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        23: from /usr/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        22: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/cli.rb:289:in `exec'
        21: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/runner.rb:129:in `run'
        20: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/runner.rb:101:in `load'
        19: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/runner.rb:101:in `each'
        18: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/runner.rb:107:in `block in load'
        17: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile.rb:247:in `load_libraries'
        16: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile.rb:247:in `each_with_index'
        15: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile.rb:247:in `each'
        14: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile.rb:265:in `block in load_libraries'
        13: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile.rb:272:in `load_libraries'
        12: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:143:in `load_libraries'
        11: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:143:in `each'
        10: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:144:in `block in load_libraries'
         9: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:159:in `load_library_file'
         8: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:170:in `load_with_context'
         7: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/profile_context.rb:170:in `instance_eval'
         6: from libraries/aws_alb.rb:3:in `load_with_context'
         5: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/dsl_shared.rb:47:in `require'
         4: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/dsl_shared.rb:47:in `eval'
         3: from libraries/aws_backend.rb:18:in `create'
         2: from /usr/lib/ruby/gems/2.7.0/gems/inspec-core-4.18.104/lib/inspec/dsl_shared.rb:33:in `require'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- aws-sdk-guardduty (LoadError)
```
With : 

```yaml
vpc_id: xxxxxx
```

And tests : 

```ruby
vpc_id = attribute("vpc_id")

control "vpc-0" do
  impact 1.0

  title "Check to see if custom VPC exists."

  tag platform: "AWS"
  tag category: 'Network'
  tag resource: "VPC"
  tag effort: 0.2

  describe aws_vpc(vpc_id) do
    only_if { aws_vpc_id != "" } .
    it { should exist }
  end
end
```

Credentials are from environment variables : 

```bash
$ ❯ env|grep AWS
AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxx
AWS_DEFAULT_REGION=eu-west-3
AWS_REGION=eu-west-3
```

# Describe the problem

```bash
$ inspec detect -t aws://
Test infrastructure

 ────────────────────────────── Platform Details ────────────────────────────── 

Name:      aws
Families:  cloud, api
Release:   train-aws: v0.1.15, aws-sdk-core: v3.94.0
```
Any idea how fix that ? 
Thanks.

**Comment by omerdemirok** [comment]
Hi @nlamirault,
Seems like you are using an old version of InSpec (and train plugin) that doesn't have the `aws-sdk-guardduty` dependency. 

First, update InSpec (preferably to the latest version), then re-try.
It is always good to start with a fresh environment/profile.
Remember to delete the `inspec.lock` if you re-use the existing profile.

**Comment by nlamirault** [comment]
OK i try a fresh install like that : 

```ruby
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Dependencies

gem 'inspec', '~> 4.23', '>= 4.23.15'
gem 'inspec-bin', '~> 4.23', '>= 4.23.15'
```

```bash
$ bundle config set path vendor/bundle
$ bundle install
You are replacing the current local value of path, which is currently "./gem"                                                                                                                                       
Fetching gem metadata from https://rubygems.org/........                                                                                                                                                            
Fetching concurrent-ruby 1.1.7                                                                                                                                                                                      
....

$ grep thor Gemfile.lock
267:      thor (>= 0.20, < 2.0)
359:    thor (1.0.1)

$ vendor/bundle/ruby/2.7.0/bin/inspec exec . -t aws:// --input-file=attributes/staging.yml
Traceback (most recent call last):
        16: from /home/nicolas/Projects/portefaix/vendor/bundle/ruby/2.7.0/bin/inspec:23:in `<main>'
        15: from /home/nicolas/Projects/portefaix/vendor/bundle/ruby/2.7.0/bin/inspec:23:in `load'
        14: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-bin-4.23.15/bin/inspec:10:in `<top (required)>'
        13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-core-4.23.15/lib/inspec/cli.rb:3:in `<top (required)>'
        10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         8: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-core-4.23.15/lib/inspec/utils/deprecation/deprecator.rb:1:in `<top (required)>'
         7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-core-4.23.15/lib/inspec/utils/deprecation/config_file.rb:4:in `<top (required)>'
         4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /home/nicolas/.gem/ruby/2.7.0/gems/inspec-core-4.23.15/lib/inspec/config.rb:7:in `<top (required)>'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- thor (LoadError)
make: *** [aws.mk:74: inspec-test] Error 1
```

**Comment by nlamirault** [comment]
Sorry i forget `bundle exec`. It works. Thanks.
